name: brewdigital-consent-manager

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn publish --access public
